import { it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { parseEnv } from "node:util";
import { randomUUID } from "node:crypto";
import pg from "pg";
it("encrypted backup restores immutable records into a separate empty recovery database", async () => {
  const env = parseEnv(readFileSync(".env.local", "utf8")),
    url = new URL(env.ART_MIGRATION_DATABASE_URL!);
  if (
    !["localhost", "127.0.0.1"].includes(url.hostname) ||
    url.port !== "55322"
  )
    throw new Error("Recovery tests require local port 55322.");
  const owner = new pg.Client({ connectionString: url.toString() });
  await owner.connect();
  expect(
    (await owner.query("select kind from art_checkin.environment")).rows[0]
      .kind,
  ).toBe("demo");
  const database = "art_recovery_" + randomUUID().replaceAll("-", ""),
    pass = randomUUID() + randomUUID();
  const expected = (
    await owner.query("select count(*)::int n from art_checkin.events")
  ).rows[0].n;
  // Credentials stay inside child process environment and ignored files.
  execFileSync(process.execPath, ["scripts/backup.mjs"], {
    env: { ...process.env, ...env, ART_BACKUP_PASSPHRASE: pass },
    stdio: "pipe",
  });
  const file = readdirSync("backups")
    .filter((f) => f.endsWith(".artbackup"))
    .sort()
    .at(-1)!;
  const bytes = readFileSync("backups/" + file);
  expect(bytes.includes(Buffer.from("Amelia"))).toBe(false);
  await owner.query('create database "' + database + '"');
  const restoreUrl = new URL(url);
  restoreUrl.pathname = "/" + database;
  const recovery = new pg.Client({ connectionString: restoreUrl.toString() });
  await recovery.connect();
  try {
    await recovery.query(
      "create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[])",
    );
    await recovery.query(
      readFileSync("supabase/fixtures/demo_access.sql", "utf8"),
    );
    await recovery.query(
      readFileSync("supabase/migrations/001_art_checkin.sql", "utf8"),
    );
    await recovery.query("update art_checkin.environment set kind='live'");
    const id = (await recovery.query("select id from art_checkin.environment"))
      .rows[0].id;
    mkdirSync("tmp", { recursive: true });
    const restoreEnv = {
      ...env,
      ART_APP_MODE: "live",
      ART_EXPECTED_DATABASE_ID: id,
      ART_MIGRATION_DATABASE_URL: restoreUrl.toString(),
      ART_BACKUP_PASSPHRASE: pass,
    };
    writeFileSync(
      "tmp/.env.recovery-test",
      Object.entries(restoreEnv)
        .map(([k, v]) => k + "=" + v)
        .join("\n"),
      { mode: 0o600 },
    );
    const childEnv = { ...process.env, ART_ENV_FILE: "tmp/.env.recovery-test" };
    execFileSync(process.execPath, ["scripts/restore.mjs", "backups/" + file], {
      env: childEnv,
      stdio: "pipe",
    });
    expect(
      (await recovery.query("select count(*)::int n from art_checkin.events"))
        .rows[0].n,
    ).toBe(expected);
    expect(
      (await recovery.query("select count(*)::int n from art_checkin.students"))
        .rows[0].n,
    ).toBe(16);
    expect(
      (await recovery.query("select count(*)::int n from art_checkin.sessions"))
        .rows[0].n,
    ).toBe(0);
    expect(() =>
      execFileSync(
        process.execPath,
        ["scripts/restore.mjs", "backups/" + file],
        { env: childEnv, stdio: "pipe" },
      ),
    ).toThrow();
    const original = (
      await owner.query("select count(*)::int n from art_checkin.events")
    ).rows[0].n;
    expect(original).toBe(expected);
  } finally {
    await recovery.end();
    // The exact database is locally generated by this test, never a user database.
    await owner.query('drop database "' + database + '"');
    await owner.end();
  }
}, 30000);
