-- Artison Hallow isolated schema. Review before applying.
create schema if not exists artison_hallow;
create extension if not exists pgcrypto;
create table artison_hallow.households(id uuid primary key default gen_random_uuid(), caregiver_name text not null, email text not null, phone text, created_at timestamptz not null default now());
create unique index ah_household_email on artison_hallow.households(lower(email));
create table artison_hallow.children(id uuid primary key default gen_random_uuid(), household_id uuid not null references artison_hallow.households on delete cascade, first_name text not null, age_band text not null, created_at timestamptz not null default now());
create table artison_hallow.offerings(id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, status text not null check(status in('draft','published','archived')), duration_minutes int not null, single_price_cents int, series_price_cents int, capacity int not null, age_band text, materials_included boolean not null default true, rules jsonb not null default '{}');
create table artison_hallow.occurrences(id uuid primary key default gen_random_uuid(), offering_id uuid not null references artison_hallow.offerings, starts_at timestamptz not null, ends_at timestamptz not null, local_timezone text not null default 'America/Chicago', capacity int not null, room_key text, instructor_key text, status text not null default 'scheduled');
create table artison_hallow.interests(id uuid primary key default gen_random_uuid(), household_id uuid not null references artison_hallow.households, child_count int not null, age_bands text[] not null, program_slugs text[] not null, preferred_days text[], preferred_times text[], flexible boolean not null default false, marketing_consent boolean not null default false, created_at timestamptz not null default now());
create table artison_hallow.provisional_slots(id uuid primary key default gen_random_uuid(), program_slug text not null, label text not null, quota int not null, active boolean not null default true);
create table artison_hallow.early_reservations(id uuid primary key default gen_random_uuid(), household_id uuid not null references artison_hallow.households, child_id uuid not null references artison_hallow.children, provisional_slot_id uuid not null references artison_hallow.provisional_slots, status text not null, deposit_cents int not null, policy_version text not null, policy_accepted_at timestamptz not null, paid_at timestamptz, refund_due_at timestamptz, extended_until timestamptz, square_order_id text, square_payment_id text, square_refund_id text, created_at timestamptz not null default now(), unique(child_id,provisional_slot_id));
create table artison_hallow.invitations(id uuid primary key default gen_random_uuid(), early_reservation_id uuid not null references artison_hallow.early_reservations, offering_id uuid not null references artison_hallow.offerings, expires_at timestamptz not null, status text not null default 'pending', responded_at timestamptz);
create table artison_hallow.bookings(id uuid primary key default gen_random_uuid(), household_id uuid not null references artison_hallow.households, child_id uuid not null references artison_hallow.children, offering_id uuid not null references artison_hallow.offerings, status text not null, total_cents int not null, deposit_credit_cents int not null default 0, payment_status text not null default 'unpaid', square_order_id text, square_payment_id text, created_at timestamptz not null default now());
create table artison_hallow.booking_occurrences(booking_id uuid not null references artison_hallow.bookings on delete cascade, occurrence_id uuid not null references artison_hallow.occurrences, primary key(booking_id,occurrence_id), unique(occurrence_id,booking_id));
create table artison_hallow.seat_holds(id uuid primary key default gen_random_uuid(), child_id uuid not null references artison_hallow.children, occurrence_id uuid not null references artison_hallow.occurrences, checkout_key uuid not null, expires_at timestamptz not null, status text not null default 'held', unique(child_id,occurrence_id));
create table artison_hallow.waitlist(id uuid primary key default gen_random_uuid(), household_id uuid not null references artison_hallow.households, child_id uuid not null references artison_hallow.children, offering_id uuid references artison_hallow.offerings, provisional_slot_id uuid references artison_hallow.provisional_slots, created_at timestamptz not null default now());
create table artison_hallow.payment_events(event_id text primary key, event_type text not null, payload jsonb not null, received_at timestamptz not null default now(), processed_at timestamptz);
create table artison_hallow.refunds(id uuid primary key default gen_random_uuid(), early_reservation_id uuid references artison_hallow.early_reservations, booking_id uuid references artison_hallow.bookings, amount_cents int not null, status text not null, square_refund_id text unique, failure_reason text, created_at timestamptz not null default now());
create table artison_hallow.content_versions(id uuid primary key default gen_random_uuid(), content_key text not null, status text not null check(status in('draft','published','archived')), version int not null, payload jsonb not null, created_at timestamptz not null default now(), unique(content_key,version));
create table artison_hallow.audit_log(id bigserial primary key, actor text not null, action text not null, entity_type text not null, entity_id text, data jsonb not null default '{}', created_at timestamptz not null default now());
alter table artison_hallow.households enable row level security; alter table artison_hallow.children enable row level security; alter table artison_hallow.early_reservations enable row level security; alter table artison_hallow.bookings enable row level security;
-- Server service role owns writes. Add narrowly scoped authenticated policies with the production auth implementation; do not expose service-role credentials to browsers.
insert into artison_hallow.offerings(slug,name,status,duration_minutes,single_price_cents,series_price_cents,capacity,age_band,materials_included) values
('homeschool-art','Homeschool Art','draft',60,3500,12000,12,'school-age',true),
('after-school-art','After-school Art','draft',60,3500,12000,12,'school-age',true),
('little-makers','Little Makers','draft',45,3500,12000,8,'3-5',true),
('mini-camps','Mini Camps','draft',180,6500,24000,12,'configured-per-camp',true),
('creation-station','Creation Station','draft',60,2000,null,12,'family',true);
